[build]
  publish = "public"
  command = "echo 'No build required'"

[[redirects]]
  from = "/api/*"
  to = "https://okeyproje-3.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 